apiVersion: v1
kind: Secret
metadata:
  name: cdp-dev-green-cluster
  labels:
    argocd.argoproj.io/secret-type: cluster
    cluster: cdp-dev-green
    stage: dev
  namespace: argo
type: Opaque
stringData:
  name: awsdc-kcl-com-cdp-dev-green
  server: https://5B5140E455E7D59D5393BF1B56637C36.gr7.ap-northeast-2.eks.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
          "clusterName": "awsdc-kcl-com-cdp-dev-green",
          "roleARN": "arn:aws:iam::658379516860:role/argo-deployer"
      },
      "tlsClientConfig": {
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQ3BFL205WHdlZmd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBME1USXdNREkzTXpSYUZ3MHpOREEwTVRBd01ETXlNelJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURnQ0NFSVFKVDc3cXN2a1c4MVdsZFU4RkJTYmlCSTl6OUNnTFFSM2p6ZERLWHZ4T09SS0xhd0lVTmEKUTZGUW5VMVJqYjl0Y1NFSHVJd1FMeThIK0tSQmVEZ0puUW1wZFlQcTJoeWdvNVQ2VHlZbkJsM2xmdmh2anRkSApyYkdGQVYxQ0NiMDlsNXhuWHg5Tm9MdEFBcVN5ekNpZEpRUS9wdVFmTTNnRGdRRnloQ2Q3Z3l6cEdYdXNtTE1BClgyVTR4b0k5NGxXVEpaQjllTmJWaU15QTlzMW8vTCtPMTZ0OVZRU3h1ZDZQajJ3WXE0ZkNqYnBhMjdrNFN0emsKT1NISnI5Q2gwUXF6bUVHVFVXTGc0Q0t0cjN4TjEzaE93cytDWmFqN3A2UklRVnBXR1ZtZUVTc2tWa3lHUmY3YQpvV2pZYnJMZzR0MXE4RysyS2g1ZE9WdDhLUVUvQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUQmhGVEVGY3JOaHF1c2p4TmtWRFFmeVJKYXlqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRREd4WEE4ZWNLNwpFMEhaU3VueFl5TWZkeGg3UmpTcEFCazlaQUppZVN5d2xhWVJVaWlpcG85RFViOWtnd0IvMGQzRnQ3NDdqWnZVClM2Uk9zMjdySU1JVXVZL3hhWm1BTkZ5VlYyc0k5WE9WZDR0TFNRRm8zK0hzUFhRRjhCdTM3dkhyd2FxMk00eGgKTWJrZGlWTEwrUTFPZ2R2QTg5aWVPR2YzN092aHh0MzRYUmFjOFAvNnM1QllPZmdPWWVwSkZkTjlHSVlBbWs2egpKOHVxcWczNHV4ZFhIaGFtdCt2cjh5cmVvemVGeGs0R3krS3ZuaUZlUXRrdUlPZGducUh0TURtZEpXMktSVDdECmJhdGxyNVd4UXJGaHA3c3VOL3k5VWRtaGMrd0dBZGNwci94b0tNa0VaaG5HSnBaWktpbFZXYWx1eU5BTk1zSUIKUTFDRi9Ra0dlRks4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }
