apiVersion: v1
kind: Secret
metadata:
  name: shr-green-cluster
  labels:
    argocd.argoproj.io/secret-type: cluster
    cluster: shr-green
    stage: shr
  namespace: argo
type: Opaque
stringData:
  name: awsdc-kcl-shr-com-green
  server: https://7B3CE9EF09CC751624802992A2250E22.gr7.ap-northeast-2.eks.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
          "clusterName": "awsdc-kcl-shr-com-green",
          "roleARN": "arn:aws:iam::527449218003:role/argo-deployer"
      },
      "tlsClientConfig": {
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1Ea3hNVEF5TVRNME4xb1hEVE16TURrd09EQXlNVE0wTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTG4vCjA2cFdPRkdEdEFOdWRCWWFJMjlVd2RvQ2p0SUxCYTVNNEhhbmVEWlZ1OG5mWmxia1lQdWpadVMzeXRvVkRyVVkKelJwcm4vSjJhWlpYV3ZydHJMVURXUk44ZGtUMGV2VE9jQ29keGxsc055V1RIRnZkMWtOVUNpTFplYWhFSElJTgpmZHBabkJOT0FadTZ4M3JnYWcwdmxlak9uaytiY3BHZFNMTGlvUDJwYWFXZGJTcXFzc0VlQk1NNWNJVUU0SW5VCnFOWkwzSEVpZjVRODFuYlhCSnFkUDN1d1FwK2duL3BMMGdtQzl2aXVWdDZCeUtSSmphSC9rZnJNYVU3WjN6cjgKaXdER2VxejRGVXZQeGpnckd2OGNqZm0ySmVyUmRyTHlNZXh6VmZzWFVjVmp1R1JNK2dhOHFHN3NLRWhkazlETwpySTFSMnVLK3dML2xhYUhBL1I4Q0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKTjA5OVBNbzlrcSsrOFdzM3dVWU01SG9pSXVNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR0RrRHdCN1oycEkwS3RHZjcxWQoxMXExVkJGdU9sV25CbkdFc21MOXNIY1lJQ01XNzlWditVU2JNZHMxU3hVaElPNHNqMlhqLzRXN1NqTVN0QkpJCkk1dXRYSFJqb0JuSVNGU0VmNVgrRG8rclZ4Z3ZxTThOMkE5K00rd2wzYjRRamI0bzFERlA5anI4Wm1zeis0WGcKMlRqV1pKSjlpOGJqcVNWQmp1NmFIUGpDSndDb29hTUE4ckg2azJRc0FEWjNhVEJNdDZ4cC94SHNydlBTdjRGLwp4dDdjbVRzd01yOE9pOXo4cTJZMTdrejQ3MkovZmo3VTRIUjZNTElvcElndkNleEVqVnJ1UFNDS0lHOG9lVllWCkdodFQzQ3BrUEhZWTFQWVFYT3lFTXhpcEM3TGJINnlCV3B4cm16Zms1MlNjYkIwaXFKbE9iRGxFRjdUeXVmMjUKa0hFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
      }
    }
