apiVersion: v1
kind: Secret
metadata:
  name: shr-dev-cluster
  labels:
    argocd.argoproj.io/secret-type: cluster
    cluster: shr-dev
    stage: shr
  namespace: argo
type: Opaque
stringData:
  name: awsdc-kcl-shr-com-dev
  server: https://C6E8E8C374C0E2362B6E37602465994D.gr7.ap-northeast-2.eks.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
          "clusterName": "awsdc-kcl-shr-com-dev",
          "roleARN": "arn:aws:iam::527449218003:role/argo-deployer"
      },
      "tlsClientConfig": {
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1Ea3lOVEExTURjeU0xb1hEVE16TURreU1qQTFNRGN5TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWRPClRjai9oR0FjcG1NTktlSjVkYnByOGw1bmJCMzVvbEN6WTN1NlU2OEoxeFlkZHlrU1U2NWtSQXBwc0xMRGE0QVoKbXB5dEV1UG8vODlvbG1LYS9TU1dvaWVHZGZCUDBRRjI1a2htYzZqRDRlYld1b2RLdVZDODJCZXY5Yi9GUXBxUAp0Z3Nwd1VoWVlVbXUxc202SGhsU3pUcEdqVE5SMGZSdlBRSFVXM0dNNW5QRzV5UjY5ekJBMDdsUHZKdllqaUZKCklkN0F4VngyUGhGTnM1TEJ3dXp4REErc1RlbEpuQ3Z5dThES0dmbmFSUTlYR3RJVEdmU21mYTdTajBDWWlGNWEKak13R0MxYys0SERPWjdnZDBrWjdCdXBQVUVQbWQ0STg3cGdLbXgxcjRRdzBBNGdBWFFVb2N0ZGVPZ1dNWEtpdApKZWt0Wk45dXh5SVVDYVJhbkxrQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZOODd2Q3VpUUtIT2dKZHUrNG9IV2JoVFEwK0FNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTVRXMlc4cWlxcmpaTFBIVWNKYgptN1owcldxUUErRmhzcmd1MnFVU0l6VEpXVndLM3VjK3dVT0tVTExQS0RlT1FITVVIWjlIMm5Wc3hEN2Z6eGlTCkZUekxIcWx1V1A2WTQ0cmhwWEE3MDhldzdWRzU4OFZ0NFpKd25EYmUvWExQeEpLQXJjYURDMWYvMTd2S3pnbXAKRW9sZW5XazZyVUU2SzFrRU5mbDYvcHZjSENIQXc3UWlHdi9FK3VvOEwzQUZyYW5LeXF6YXpoQ2ZINGpVdXArRgpwZkxVVm1UMlNoYkpNQk50WUFCZzlabFl0c05iSVlqOWNCOFliMGpIUU9JZVhJM1UydmRyTmNUUTRZQ3p1bkFtClBtVG5UTGFPRy8vcnhRTkdvc2t3TjFkL3VFY1RSMC9nNmxtbEJNK1YxZ1Z6T2hXUjZwNTh5MVU2S2FnLzcwcGsKN3RzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
      }
    }
