apiVersion: v1
kind: Secret
metadata:
  name: local
  labels:
    argocd.argoproj.io/secret-type: cluster
    cluster: local
    stage: local
  namespace: argocd
type: Opaque
stringData:
  name: local
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJVHhya2ZRaHZHZDh3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOekV6T1RNMk16Y3dNQjRYRFRJME1EUXlOREExTWpZeE1Gb1hEVEkxTURReQpOREExTWpZeE1Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFcUdJYVkrc3hDMTJpZTgKbW84UENCRVlncVlhYUNGa050M1MrMFptdHBWc2hMbGtGOEk5a1J5OG00ZWRTN0J6ZndUQzJJRDMybDFLMEgveQpTVHhvU3pPalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVGliOUNkUkRVdmk1UFhKTlZPcVJCUE0xOHdrREFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlCV3dyLzNqVk5mcmV2UENRM29tZmxweEx1cURUTVJMUmJiM3RrZDQ4MktCZ0loQVA4bG5CcTJaVzhNWW9yawpCWmxRZjBvMG56cXZtcXhrY0V5a0F3LzgwdGU2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTVRNNU16WXpOekF3SGhjTk1qUXdOREkwTURVeU5qRXdXaGNOTXpRd05ESXlNRFV5TmpFdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTVRNNU16WXpOekF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTbFBYZ3lzSUNGT3VKK1c0YTgvd1BpQ3orVXIvYnhXQ3Q2K1lSdnEyTFgKRWpKVkxzbFZlZWpNNnl5bzBWcVBYdFdvY0tBNHlQbU01TzZHVkR6b3JaeWJvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTRtL1FuVVExTDR1VDF5VFZUcWtRClR6TmZNSkF3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUsvcjh4OFZsVWxNOXEvTVczSGIxcmliQ3IwaExGK1YKQnJXSGJPd0FWcHQrQWlFQWliSVBDNlJsSklZWFhkVlBFRGkyalNqampUZEJ4NnpxUnlUbXFnMWd3T0E9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }