apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-appset
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: cluster
              operator: In
              values:
              - local
        values:
          revision: master
  template:
    metadata:
      name: 'argo-cd'
    spec:
      # project: '{{metadata.labels.stage}}'
      project: 'shr'
      source:
        helm:
          valueFiles:
          - values.yaml
        repoURL: https://github.com/rodgh21/argo.git
        targetRevision:  'master'
        path: ./
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'argocd'
