apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jenkinsrudgh21-appset
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: cluster
              operator: In
              values:
              - shr
        values:
          revision: master
  template:
    metadata:
      name: "jenkins"
    spec:
      syncPolicy:
        automated: {}
      project: "{{metadata.labels.stage}}"
      source:
        helm:
          valueFiles:
          - values.yaml
        repoURL: https://github.com/rodgh21/jenkins-helm.git
        targetRevision: "{{values.revision}}"
        path: ./
      destination:
        server: "{{server}}"
        namespace: "jenkins"
